version: '3'
services:
  mysql:
    image: mysql:8.0.25
    restart: unless-stopped
    container_name: mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
        - tosc
  keycloak:
    image: jboss/keycloak
    restart: unless-stopped
    container_name: tosc-keycloak
    env_file: .env
    environment: 
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak-data:/var/lib/keycloak/data
    networks:
        - tosc
  toscdb:
    image: mongo
    restart: unless-stopped
    container_name: tosc-db
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - keycloak
    volumes:
      - ./db:/data/db
    networks:
      - tosc
  cms:
    image: strider2023/tosc-portal-cms:0.1.1
    restart: unless-stopped
    container_name: tosc-portal-cms
    env_file: .env
    environment:
        DATABASE_CLIENT: ${DATABASE_CLIENT}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
        - toscdb
    ports:
      - '1337:1337'
    networks:
      - tosc
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
  server:
    image: strider2023/tosc-app-server:0.1.0
    restart: unless-stopped
    container_name: tosc-app-server
    env_file: .env
    environment:
        APPLICATION_PORT: ${APPLICATION_PORT}
        KEYCLOAK_ENDPOINT: ${KEYCLOAK_ENDPOINT}
        KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        KEYCLOAK_GRANT_TYPE: ${KEYCLOAK_GRANT_TYPE}
        KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        KEYCLOAK_SCOPE: ${KEYCLOAK_SCOPE}
        STRAPI_AUTH_URL: ${STRAPI_AUTH_URL}
    depends_on:
        - cms
    ports:
      - '4000:4000'
    networks:
      - tosc
  tosc-portal:
    image: strider2023/tosc-portal:0.1.2
    restart: unless-stopped
    container_name: tosc-portal
    env_file: .env
    depends_on:
        - server
    ports:
      - '8000:80'
    environment:
      STARPI_URL: ${STARPI_URL}
      ENABLE_GATSBY_REFRESH_ENDPOINT: ${ENABLE_GATSBY_REFRESH_ENDPOINT}
    networks:
        - tosc
  tosc-web-app:
    image: strider2023/tosc-web-app:0.1.0
    restart: unless-stopped
    container_name: tosc-web-app
    env_file: .env
    depends_on:
      - server
    ports:
      - '3000:80'
    environment:
      TOSC_APP_SERVER_GRAPHQL: ${TOSC_APP_SERVER_GRAPHQL}
      TOSC_CMS_URL: ${TOSC_CMS_URL}
    networks:
      - tosc
networks:
    tosc:
        driver: bridge

volumes:
    toscdb: